### ISSUE TITLE
Access Request for slamp

### ISSUE THREAD

**Issue by slamp** [aurae-runtime/authz#4]
I have read and agree to the [terms and conditions [(https://github.com/aurae-runtime/authz/blob/main/TERMS.md) of the Aurae project.

I agree not to disclose any of the concepts, source code, or intentions found within this organization without explicit written permission for Kris Audrey Nóva [@kris-nova](https://github.com/kris-nova).

Additionally I agree to abide by the CLA (contributor license agreement) or all contributions made within the `aurae-runtime` GitHub organization.

**Comment by slamp** [comment]
I agree with pleasure to the term ;-)

**Comment by kris-nova** [comment]
I will need a full legal name in order to accept.

**Comment by slamp** [comment]
Email sent with my full name.

**Comment by kris-nova** [comment]
Welcome
